version: "3"
services:
  uwsgi:
    container_name: "uwsgi"
    build: ./app
    volumes:
      - ./app:/var/www/
    ports:
      - "3031:3031"

  nginx:
    container_name: "nginx"
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - uwsgi
    ports:
      - "80:80"
