version: '3'
services:
  nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    network_mode: bridge
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  ubuntu:
    build: ubuntu
    image: ubuntu
    container_name: ubuntu-server
    network_mode: bridge
    expose: 
      - "80"
    environment:
      - VIRTUAL_HOST=server.localhost
