version: '3'
services:
  geth:
    build: geth
    image: geth
    container_name: geth
    command: >
      --networkid 1220
      --syncmode=full
      --cache 4098
      --nodiscover
      --maxpeers=25
      --datadir=/root/.ethereum
      --rpc
      --rpcaddr=0.0.0.0
      --rpcport=8545
      --rpccorsdomain='*'
      --rpcapi=admin,db,debug,eth,miner,net,personal,shh,txpool,web3
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - ./geth/.ethereum:/root/.ethereum