version: '3'
services:
  ipfs_private:
    build: ipfs_private
    image: ipfs_private
    container_name: ipfs_private
    ports:
      - "4001:4001"
      - "15001:5001"
      - "8080:8080"
      - "8081:8081"
    volumes:
      - "./ipfs_dir/.ipfs:/root/.ipfs"
